# Generated by Django 4.1.5 on 2023-01-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=221, null=True, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=221, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=221, null=True, verbose_name='Nomi')),
                ('sub_title', models.TextField(verbose_name="Qo'shimcha sarlavha")),
                ('sub_title_ru', models.TextField(null=True, verbose_name="Qo'shimcha sarlavha")),
                ('sub_title_uz', models.TextField(null=True, verbose_name="Qo'shimcha sarlavha")),
                ('sub_title_en', models.TextField(null=True, verbose_name="Qo'shimcha sarlavha")),
                ('about_us', models.TextField(verbose_name='Matn')),
                ('about_us_ru', models.TextField(null=True, verbose_name='Matn')),
                ('about_us_uz', models.TextField(null=True, verbose_name='Matn')),
                ('about_us_en', models.TextField(null=True, verbose_name='Matn')),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=222, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=222, null=True, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=222, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=222, null=True, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('content_ru', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_uz', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_en', models.TextField(null=True, verbose_name='Mazmuni')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221, verbose_name='Ismi')),
                ('name_ru', models.CharField(max_length=221, null=True, verbose_name='Ismi')),
                ('name_uz', models.CharField(max_length=221, null=True, verbose_name='Ismi')),
                ('name_en', models.CharField(max_length=221, null=True, verbose_name='Ismi')),
                ('date_birth', models.CharField(max_length=50, verbose_name="Hayoti:tug'ilgan va vafot etgan yili")),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='scientists/')),
                ('biography', models.TextField()),
                ('biography_ru', models.TextField(null=True)),
                ('biography_uz', models.TextField(null=True)),
                ('biography_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Savol')),
                ('question_ru', models.CharField(max_length=1000, null=True, verbose_name='Savol')),
                ('question_uz', models.CharField(max_length=1000, null=True, verbose_name='Savol')),
                ('question_en', models.CharField(max_length=1000, null=True, verbose_name='Savol')),
                ('answer_1', models.CharField(max_length=1000, verbose_name='Javob 1')),
                ('answer_1_ru', models.CharField(max_length=1000, null=True, verbose_name='Javob 1')),
                ('answer_1_uz', models.CharField(max_length=1000, null=True, verbose_name='Javob 1')),
                ('answer_1_en', models.CharField(max_length=1000, null=True, verbose_name='Javob 1')),
                ('answer_2', models.CharField(max_length=1000, verbose_name='Javob 2')),
                ('answer_2_ru', models.CharField(max_length=1000, null=True, verbose_name='Javob 2')),
                ('answer_2_uz', models.CharField(max_length=1000, null=True, verbose_name='Javob 2')),
                ('answer_2_en', models.CharField(max_length=1000, null=True, verbose_name='Javob 2')),
                ('answer_3', models.CharField(max_length=1000, verbose_name='Javob 3')),
                ('answer_3_ru', models.CharField(max_length=1000, null=True, verbose_name='Javob 3')),
                ('answer_3_uz', models.CharField(max_length=1000, null=True, verbose_name='Javob 3')),
                ('answer_3_en', models.CharField(max_length=1000, null=True, verbose_name='Javob 3')),
                ('answer_true', models.CharField(max_length=1000, verbose_name="To'g'ri Javob")),
                ('answer_true_ru', models.CharField(max_length=1000, null=True, verbose_name="To'g'ri Javob")),
                ('answer_true_uz', models.CharField(max_length=1000, null=True, verbose_name="To'g'ri Javob")),
                ('answer_true_en', models.CharField(max_length=1000, null=True, verbose_name="To'g'ri Javob")),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
        migrations.CreateModel(
            name='ScientistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('name_ru', models.CharField(max_length=221, null=True)),
                ('name_uz', models.CharField(max_length=221, null=True)),
                ('name_en', models.CharField(max_length=221, null=True)),
                ('link_video', models.URLField()),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scientist')),
            ],
            options={
                'verbose_name': 'Filmlar',
                'verbose_name_plural': 'Filmlar',
            },
        ),
        migrations.CreateModel(
            name='ScientistFotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotogallery/')),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scientist')),
            ],
            options={
                'verbose_name': 'FotoGalareya',
                'verbose_name_plural': 'FotoGalareya',
            },
        ),
        migrations.CreateModel(
            name='ScientistEbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('name_ru', models.CharField(max_length=221, null=True)),
                ('name_uz', models.CharField(max_length=221, null=True)),
                ('name_en', models.CharField(max_length=221, null=True)),
                ('file', models.FileField(upload_to='e-books/')),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scientist')),
            ],
            options={
                'verbose_name': 'Elektron Kitoblar',
                'verbose_name_plural': 'Elektron Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='ScientistAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('name_ru', models.CharField(max_length=222, null=True)),
                ('name_uz', models.CharField(max_length=222, null=True)),
                ('name_en', models.CharField(max_length=222, null=True)),
                ('image', models.ImageField(upload_to='audio_images/')),
                ('audio', models.FileField(upload_to='audio_files/')),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scientist')),
            ],
            options={
                'verbose_name': 'Audiolavhalar',
                'verbose_name_plural': 'Audiolavhalar',
            },
        ),
    ]
