# Generated by Django 4.1.5 on 2023-01-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientist',
            options={'verbose_name': 'Allomalar', 'verbose_name_plural': 'Allomalar'},
        ),
    ]
